# Generated by Django 2.1.1 on 2018-09-07 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('album', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=50)),
                ('landscape_orientation', models.NullBooleanField()),
            ],
        ),
    ]
